# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-01 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_team_beers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='generic name', max_length=10000),
            preserve_default=False,
        ),
    ]
