# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
