# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20170307_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
